 #include<LiquidCrystal.h>
LiquidCrystal lcd(2,3,4,5,6,7);
int r1=8,r2=9,r3=10,r4=12,c1=A0,c2=A1,c3=A2;
int a=0,b=0,c,d;
int k,l,m,n,o,p;
int i,cnt,temp1,temp2,j=0;
void setup()
{
  pinMode(r1,INPUT);
  pinMode(r2,INPUT);
  pinMode(r3,INPUT);
  pinMode(r4,INPUT);
  pinMode(c1,OUTPUT);
  pinMode(c2,OUTPUT);
  pinMode(c3,OUTPUT);
  lcd.setCursor(k,j);
Serial.begin(9600);
lcd.begin(16,2);
}
void loop()
{
 pres();

}
void pres()
  {
    digitalWrite(c1,0);
    digitalWrite(c2,1);
    digitalWrite(c3,1);
    digitalWrite(r1,1);
    digitalWrite(r2,1);
    digitalWrite(r3,1);
    digitalWrite(r4,1);
    
    if(!digitalRead(r1))
    {
      lcd.setCursor(k,j);
      k++;
      while(!digitalRead(r1))
      digitalWrite(r1,1);
      delay(10);
      for(i=0;i<100;i++)
    {
      if(!digitalRead(r1))
    {
      i=0;
      cnt++;
      while(!digitalRead(r1))
      digitalWrite(r1,1);
      delay(10);
      if(cnt==3)
      break;
    }
      delay(10);
    }
    if(cnt==0)
    lcd.print("a");
    if(cnt==1)
    lcd.print("b");
    if(cnt==2)
    lcd.print("c");
    if(cnt==3)
    lcd.print("1");
      Serial.println(cnt);
      cnt=0;
    }
 
   if(!digitalRead(r2))
    {
      lcd.setCursor(k,j);
      k++;
      while(!digitalRead(r2))
      digitalWrite(r2,1);
      delay(10);
      for(i=0;i<100;i++)
    {
      if(!digitalRead(r2))
    {
      i=0;
      cnt++;
      while(!digitalRead(r2))
      digitalWrite(r2,1);
      delay(10);
      if(cnt==3)
      break;
    }
      delay(10);
    }
    if(cnt==0)
    lcd.print("j");
    if(cnt==1)
    lcd.print("k");
    if(cnt==2)
    lcd.print("l");
    if(cnt==3)
    lcd.print("4");
      Serial.println(cnt);
      cnt=0;
    }
  
    if(!digitalRead(r3))
    {
      lcd.setCursor(k,j);
      k++;
      while(!digitalRead(r3))
      digitalWrite(r3,1);
      delay(10);
      for(i=0;i<100;i++)
    {
      if(!digitalRead(r3))
    {
      i=0;
      cnt++;
      while(!digitalRead(r3))
      digitalWrite(r3,1);
      delay(10);
      if(cnt==3)
      break;
    }
      delay(10);
    }
    if(cnt==0)
    lcd.print("s");
    if(cnt==1)
    lcd.print("t");
    if(cnt==2)
    lcd.print("u");
    if(cnt==3)
    lcd.print("7");
      Serial.println(cnt);
      cnt=0;
    }
    
    
    digitalWrite(c1,1);
    digitalWrite(c2,0);
    digitalWrite(c3,1);
    digitalWrite(r1,1);
    digitalWrite(r2,1);
    digitalWrite(r3,1);
    digitalWrite(r4,1);
    
    if(!digitalRead(r1))
    {
      lcd.setCursor(k,j);
      k++;
      while(!digitalRead(r1))
      digitalWrite(r1,1);
      delay(10);
      for(i=0;i<100;i++)
    {
      if(!digitalRead(r1))
    {
      i=0;
      cnt++;
      while(!digitalRead(r1))
      digitalWrite(r1,1);
      delay(10);
      if(cnt==3)
      break;
    }
      delay(10);
    }
    if(cnt==0)
    lcd.print("d");
    if(cnt==1)
    lcd.print("e");
    if(cnt==2)
    lcd.print("f");
    if(cnt==3)
    lcd.print("2");
      Serial.println(cnt);
      cnt=0;
    }
 
   if(!digitalRead(r2))
    {
      lcd.setCursor(k,j);
      k++;
      while(!digitalRead(r2))
      digitalWrite(r2,1);
      delay(10);
      for(i=0;i<100;i++)
    {
      if(!digitalRead(r2))
    {
      i=0;
      cnt++;
      while(!digitalRead(r2))
      digitalWrite(r2,1);
      delay(10);
      if(cnt==3)
      break;
    }
      delay(10);
    }
    if(cnt==0)
    lcd.print("m");
    if(cnt==1)
    lcd.print("n");
    if(cnt==2)
    lcd.print("o");
    if(cnt==3)
    lcd.print("5");
      Serial.println(cnt);
      cnt=0;
    }
  
    if(!digitalRead(r3))
    {
      lcd.setCursor(k,j);
      k++;
      while(!digitalRead(r3))
      digitalWrite(r3,1);
      delay(10);
      for(i=0;i<100;i++)
    {
      if(!digitalRead(r3))
    {
      i=0;
      cnt++;
      while(!digitalRead(r3))
      digitalWrite(r3,1);
      delay(10);
      if(cnt==3)
      break;
    }
      delay(10);
    }
    if(cnt==0)
    lcd.print("v");
    if(cnt==1)
    lcd.print("w");
    if(cnt==2)
    lcd.print("x");
    if(cnt==3)
    lcd.print("8");
      Serial.println(cnt);
      cnt=0;
    }

      
    digitalWrite(c1,1);
    digitalWrite(c2,1);
    digitalWrite(c3,0);
    digitalWrite(r1,1);
    digitalWrite(r2,1);
    digitalWrite(r3,1);
    digitalWrite(r4,1);
    
    if(!digitalRead(r1))
    {
      lcd.setCursor(k,j);
      k++;
      while(!digitalRead(r1))
      digitalWrite(r1,1);
      delay(10);
      for(i=0;i<100;i++)
    {
      if(!digitalRead(r1))
    {
      i=0;
      cnt++;
      while(!digitalRead(r1))
      digitalWrite(r1,1);
      delay(10);
      if(cnt==3)
      break;
    }
      delay(10);
    }
    if(cnt==0)
    lcd.print("g");
    if(cnt==1)
    lcd.print("h");
    if(cnt==2)
    lcd.print("i");
    if(cnt==3)
    lcd.print("3");
      Serial.println(cnt);
      cnt=0;
    }
 
   if(!digitalRead(r2))
    {
      lcd.setCursor(k,j);
      k++;
      while(!digitalRead(r2))
      digitalWrite(r2,1);
      delay(10);
      for(i=0;i<100;i++)
    {
      if(!digitalRead(r2))
    {
      i=0;
      cnt++;
      while(!digitalRead(r2))
      digitalWrite(r2,1);
      delay(10);
      if(cnt==3)
      break;
    }
      delay(10);
    }
    if(cnt==0)
    lcd.print("p");
    if(cnt==1)
    lcd.print("q");
    if(cnt==2)
    lcd.print("r");
    if(cnt==3)
    lcd.print("6");
      Serial.println(cnt);
      cnt=0;
    }
  
    if(!digitalRead(r3))
    {
      lcd.setCursor(k,j);
      k++;
      while(!digitalRead(r3))
      digitalWrite(r3,1);
      delay(10);
      for(i=0;i<100;i++)
    {
      if(!digitalRead(r3))
    {
      i=0;
      cnt++;
      while(!digitalRead(r3))
      digitalWrite(r3,1);
      delay(10);
      if(cnt==3)
      break;
    }
      delay(10);
    }
    if(cnt==0)
    lcd.print("y");
    if(cnt==1)
    lcd.print("z");
    if(cnt==2)
    lcd.print("*");
    if(cnt==3)
    lcd.print("9");
      Serial.println(cnt);
      cnt=0;
    }
       if(!digitalRead(r4))
    {
      k--;
      while(!digitalRead(r4))
      digitalWrite(r4,1);
      delay(300 );
      Serial.println("fgk");
      lcd.setCursor(k,j);
      lcd.print(" ");
        }
  }
  
